### ISSUE TITLE
Sending an attachment with a ReadStream twice fails

### ISSUE THREAD

**Issue by philiiiiiipp** [bojand/mailgun-js#143]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
mailgun-js@0.11.2 (latest atm)

2) What platform and Node.js version? (For example Node.js 0.12 on Mac OS X)
npm 5.0.0
node v6.10.3

4) Sample source code or steps to reproduce
```
const stream = fs.createReadStream("any file");
const fileStat = fs.statSync(filePath);

const attachment = {
  data: stream,
  filename: pdfName,
  knownLength: fileStat.size,
  contentType: 'application/pdf'
}

const mailOptions1 = {
  ...
  attachment: new Mailgun.Attachment(attachment)
};

const mailOptions2 = {
  ...
  attachment: new Mailgun.Attachment(attachment)
};

Mailgun.messages().send(mailOptions1, (error, body) => {
  if (error) console.log(error);

  Mailgun.messages().send(mailOptions2, (error, body) => {
      if (error) console.log(error); // Second time it fails
      console.log('done');
  });
});
```

(Write description of your issue here, stack traces from errors and code that reproduces the issue are helpful)

It seems as if I cannot reuse the stream if I am using it in an attachment.
```
{ Error: GATEWAY_TIMEOUT
    at IncomingMessage.<anonymous> (/Users/philipp/node/dev/algas-email-bot/node_modules/mailgun-js/lib/request.js:301:15)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) statusCode: 504 }
{ Error: GATEWAY_TIMEOUT
    at IncomingMessage.<anonymous> (/Users/philipp/node/dev/algas-email-bot/node_modules/mailgun-js/lib/request.js:301:15)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9) statusCode: 504 }
```

Using `fs.readFileSync()` works fine, as well as using the path to the file. Maybe the stream does not get reseted?

**Comment by bojand** [comment]
Hello, I believe that's because it's already been read and it's finished, so there is nothing to read the 2nd try.

Simply piping content through a pass through stream should work:

```js
var stream = require('stream');

const content = fs.createReadStream("any file");
const fileStat = fs.statSync(filePath);

var stream1 = content.pipe(new stream.PassThrough())
var stream2 = content.pipe(new stream.PassThrough())

const attachment = {
  filename: pdfName,
  knownLength: fileStat.size,
  contentType: 'application/pdf'
}

const mailOptions1 = {
  ...
  attachment: new Mailgun.Attachment(Object.assign({}, {data: stream1}, attachment))
};

const mailOptions2 = {
  ...
  attachment: new Mailgun.Attachment(Object.assign({}, {data: stream2}, attachment))
};

Mailgun.messages().send(mailOptions1, (error, body) => {
  if (error) console.log(error);

  Mailgun.messages().send(mailOptions2, (error, body) => {
      if (error) console.log(error); // Second time it fails
      console.log('done');
  });
});
```
