### ISSUE TITLE
 Invalid parameter type. invoke must be of type: undefined.

### ISSUE THREAD

**Issue by sabbir-hossain** [bojand/mailgun-js#173]
I have the following error in my project.
```
 Error: Invalid parameter type. invoke must be of type: undefined.
    at constructor.impl (/home/pc/project/node_modules/mailgun-js/lib/build.js:96:17)
    at promisifyCall (/home/pc/project/node_modules/promisify-call/index.js:25:15)
    at constructor.(anonymous function) [as send] (/home/pc/project/node_modules/mailgun-js/lib/build.js:111:12)
    at EmailService.send (/home/pc/project/dist/webpack:/src/components/email/email.service.ts:66:23)
    at EmailController.send (/home/pc/project/dist/webpack:/src/components/email/email.controller.ts:26:28)
    at EmailRoute.send (/home/pc/project/dist/webpack:/src/components/email/email.routes.ts:23:24)
    at /home/pc/project/dist/webpack:/src/components/auth/authorize.ts:26:26
    at _fulfilled (/home/pc/project/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/pc/project/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/pc/project/node_modules/q/q.js:796:13)
    at /home/pc/project/node_modules/q/q.js:604:44
    at runSingle (/home/pc/project/node_modules/q/q.js:137:13)
    at flush (/home/pc/project/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
And my answer of the following question:

1) What version of the module is the issue happening on? Does the issue happen on latest version?
    *ans:*  `"mailgun-js": "^0.13.1"`

2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
    *ans:*   `v6.11.0` on `Linux` and  `v6.6.0` on `Mac OS X`

3) Does the action work when you manually perform request against mailgun using curl (or other means)?
     *ans:* I can send mail using demo `node.js` project. But same code is not working on my project where I'm using `typescript`

4) Sample source code or steps to reproduce
```
const mailgun =  require('mailgun-js')({
			apiKey: "key-api-key",
			domain: "domain-name",
		});
		
const data = {
	from: "from-address",
	to: "to-address",
	subject: "email subject",
	html: "email-body"
}

mailgun.messages().send(data, function (err, body) {
	if (err) {
		console.log("got an error: ", err);
	}
	else {
		console.log(body);
	}
});
```

**Comment by bojand** [comment]
This looks like it's Angular? Or at least client-side in browser judging by `webpack` in path? This module is meant to be used from server side within Node.js environment. Not within browser.

**Comment by sabbir-hossain** [comment]
I am sorry, but it is not `Angular` project. Ofcourse I am using `mailgun-js` for server side with Node.js environment. I am using `webpack` to compile `typescript` into `js`.
