### ISSUE TITLE
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by seerahulsingh** [bojand/mailgun-js#184]
I have been getting this error `SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` with current version of mailgun-js (0.14)

I'm using this package in a meteor app (v1.5)

backtrace
```
packages/modules.js:25322
class Mailgun {
 ^^^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at Object.exports.runInThisContext (vm.js:53:16) at /home/snow/Projects/smartportfolio/.meteor/local/build/programs/server/boot.js:332:30
at Array.forEach (native)
at Function._.each._.forEach (/home/snow/.meteor/packages/meteor-tool/.1.5.2_2.lb4o45.k6u8++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
at /home/snow/Projects/smartportfolio/.meteor/local/build/programs/server/boot.js:158:5
at /home/snow/Projects/smartportfolio/.meteor/local/build/programs/server/boot.js:388:5
at Function.run (/home/snow/Projects/smartportfolio/.meteor/local/build/programs/server/profile.js:510:12)
at /home/snow/Projects/smartportfolio/.meteor/local/build/programs/server/boot.js:387:11

```

**For now to fix this, I downgraded the mailgun-js to version v0.13, then it worked.**

**Comment by bojand** [comment]
Hello, New version `0.14` requires node 6 at least. Upgrade meteor to version 1.6 (which has node 8) and I believe that should fix it.
