### ISSUE TITLE
mailgun.messages is not a function

### ISSUE THREAD

**Issue by KrishA199** [bojand/mailgun-js#185]
1) What version of the module is the issue happening on? Does the issue happen on the #latest version?
I am using the latest version
2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
v8.4.0 Windows 10

Issue:
mailgun.messages().send(data, function (error, body) {
                ^

TypeError: mailgun.messages is not a function
    at IncomingMessage.<anonymous> ()
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by KrishA199** [comment]
The issue got resolved.
