### ISSUE TITLE
Get a 404 error domain not found

### ISSUE THREAD

**Issue by FlorianBenLamine** [bojand/mailgun-js#227]
1) What version of the module is the issue happening on? Does the issue happen on latest version?
^0.22.0

2) What platform and Node.js version? (For example Node.js 6.9.1 on Mac OS X)
Node.js 8.12.0 - Windows 10

4) Sample source code or steps to reproduce
I test : https://github.com/marchfederico/email2spark

```
var api_key = process.env.MAILGUN_API_KEY;
var emaildomain = process.env.DOMAIN;
var mailgun = require('mailgun-js')({apiKey: api_key, domain: emaildomain});
```
what I do :
```
set MAILGUN_API_KEY='xxxxxxxxxxxxxxxxx'
set DOMAIN= 'xxxx.fr'
```

I get the following 404 - Error: Domain not found when I receive an email:

```
C:\Users\FBL\Documents\GitHub\email2spark1>node email2spark.js
App server listening on 3000
New room created: test2
Adding: xx
Adding: xx
Left room
{ Error: Domain not found: xxx.fr
    at IncomingMessage.res.on (C:\Users\FBL\Documents\GitHub\email2spark1\node_modules\mailgun-js\lib\request.js:327:17)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9) statusCode: 404 }

```

Any help would be much appreciated.

**Comment by FlorianBenLamine** [comment]
Same problem with my subdomain : www.mg.xxx.fr

>{ Error: Domain not found: www.mg.xxx.fr
    at IncomingMessage.res.on (G:\Be Activ'IT\_CloudStation\Répertoires Privés\Bot\email2spark2\node_modules\mailgun-js\lib\request.js:327:17)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9) statusCode: 404 }

**Comment by FlorianBenLamine** [comment]
Just edit mailgun-js/lib/mailgun.js line 26 : 

> this.host = options.host || 'api.mailgun.net'

 by 

> this.host = options.host || 'api.eu.mailgun.net'

I have contact mailgun support : 

> Hi, Thank you for contacting Mailgun support. You'll need to ensure that your code and/or library is calling the correct URL. The API base URL in the US and EU regions differ (you can see the EU URL on the Domains tab > click on the domain > it'll be in the Domain Information section). this is the most likely reason you're seeing this particular error. Regards, Jeff | Mailgun Support

**Comment by JuanIrache** [comment]
It's still not clear how to do this correctly 5 years later
