### ISSUE TITLE
Attachments error

### ISSUE THREAD

**Issue by thomasf1** [bojand/mailgun-js#92]
When trying to add a attachment to a otherwise working Mailgun request (tried a url and a local file), there is an error:

    TypeError: Cannot read property 'path' of undefined on mailgun-js/node_modules/form-data/lib/form_data.js:195

I´m using it with meteor wrapper which I updated to the latest npm version.

The corresponding stack trace:
`
Exception while invoking method 'users/email-confirmation-request' TypeError: Cannot read property 'path' of undefined
    at FormData._getContentDisposition (/Users/tom/Dev/rentkit/packages/colldo:meteor-mailgun-api/.npm/package/node_modules/mailgun-js/node_modules/form-data/lib/form_data.js:195:43)
    at FormData._multiPartHeader (/Users/tom/Dev/rentkit/packages/colldo:meteor-mailgun-api/.npm/package/node_modules/mailgun-js/node_modules/form-data/lib/form_data.js:169:33)
    at FormData.append (/Users/tom/Dev/rentkit/packages/colldo:meteor-mailgun-api/.npm/package/node_modules/mailgun-js/node_modules/form-data/lib/form_data.js:64:21)
    at Request.prepareFormData (/Users/tom/Dev/rentkit/packages/colldo:meteor-mailgun-api/.npm/package/node_modules/mailgun-js/lib/request.js:171:17)
    at Request.request (/Users/tom/Dev/rentkit/packages/colldo:meteor-mailgun-api/.npm/package/node_modules/mailgun-js/lib/request.js:57:12)
    at [object Object].Mailgun.request (/Users/tom/Dev/rentkit/packages/colldo:meteor-mailgun-api/.npm/package/node_modules/mailgun-js/lib/mailgun.js:71:14)
    at [object Object].constructor.(anonymous function) [as send] (/Users/tom/Dev/rentkit/packages/colldo:meteor-mailgun-api/.npm/package/node_modules/mailgun-js/lib/build.js:101:24)
    at [object Object].constructor._send (packages/colldo_mailgun-api/mailgun-api.js:84:1)
    at [object Object].constructor.send (packages/colldo_mailgun-api/mailgun-api.js:74:1)
    at sendEmail (server/email.coffee:82:14)
    at dispatchNotification (server/notifications.coffee:872:3)
    (...)
`

**Comment by bojand** [comment]
I am not familiar with the meteor package. Please provide sample code using this library that reproduces the problem Thanks..

**Comment by jamiter** [comment]
This can be reproduced (in normal node and Meteor) by adding a `v:` property with an undefined value in combination with an attachment. It works without issues if the attachment is not there.

```javascript
// mailgun setup here, nothing special

var message = {
  from: "someone@example.com",
  to: "someoneElse@exampe.com",
  text: "this isn't gonna work",
  attachment: "./filename.ext" // Or any other way to define attachments: In my case new Attachment
}

message["v:whatSoEvery"] = undefined;
```

A workaround is double checking that your not passing any undefined values.

Disclaimer: I'm not sure if `v:` properties are the only issue, but it's a way I was able to reproduce it.

**Comment by jamiter** [comment]
Thanks for the quick fix!

**Comment by jamiter** [comment]
Hm, looking at the code, this would prevent anyone from setting the value to `0`. You now have a `if (value)` check, but a `if (value != null)` would only filter `null` and `undefined`.

**Comment by bojand** [comment]
Doh! Thanks. Updated and published.

**Comment by jamiter** [comment]
Awesome, thanks!
